### ISSUE TITLE
iCal feed

### ISSUE THREAD

**Issue by Ern-st** [fyntech/fyntech#10]
It would be nice if we could generate an ics feed, so you could import the events into your own mail/calendar client

**Comment by fALKENdk** [comment]
Link to feed and separate feeds still needed.
But current feeds works with: http://fyntech.dk/events.ics

**Comment by Ern-st** [comment]
I've added the "real" times now, but I'm no ruby shark so I couldn't find a way to generate the timestamps in UTC, I've had to resort to an ugly fix where we minus 7200 seconds (2 hours) from the generated timestamp in order to get the correct time in UTC. There's got to be a better solution…

**Comment by Ern-st** [comment]
Now converting to real UTC in c59ff293339197c87faa9151392a0e21a065f07c 😄

**Comment by Ern-st** [comment]
done: [add name, description & update interval ](http://stackoverflow.com/questions/17152251/specifying-name-description-and-refresh-interval-in-ical-ics-format)

**Comment by Ern-st** [comment]
done: add description and summary to events

**Comment by Ern-st** [comment]
done: create helper function to restrict lines to 75 characters in length. Move down a line add a " " and insert rest of line, rinse and repeat.

**Comment by Ern-st** [comment]
done: don't add location if it's specified as TBD or TBA

**Comment by Ern-st** [comment]
todo: figure out why Google calendar doesn't always update events in changes. We're probably missing some version tag or some such…

**Comment by Ern-st** [comment]
GCal is updating now! 🚀 Issue was fixed in 2734700
