### ISSUE TITLE
GET data from Meetup.com

### ISSUE THREAD

**Issue by Ern-st** [fyntech/fyntech#2]
CODE-Odense events https://api.meetup.com/CODE-Odense/events
Maybe we can use https://github.com/18F/jekyll-get ?

**Comment by carentsen** [comment]
For those services that does not expose an API, we can maybe use something like : https://staticman.net/ ? 
Haven't looked much into it,  but it seems pretty neat

**Comment by Ern-st** [comment]
This should be doable now that @KasperChristensen has got Travis CI up & running 💃

**Comment by fALKENdk** [comment]
Jekyll-get doesn't seem to support API keys, but maybe we can use:

- https://rubygems.org/gems/omniauth-meetupt
- https://rubygems.org/gems/rMeetup
- https://rubygems.org/gems/meetup_client

**Comment by Ern-st** [comment]
Yes, that's an option now with Travis… but… how can we keep the API key secret? 🔑

**Comment by fALKENdk** [comment]
It can be set as a Travis variable, like the deploy key.
They are supplied by Travis doing deploy, and not shown.
