### ISSUE TITLE
Scraping Prosa.dk

### ISSUE THREAD

**Issue by carentsen** [fyntech/fyntech#37]
Scrape prosa.dk for events, but only those from Fyn

**Comment by Ern-st** [comment]
and possibly exclude non tech events? things like "stress handling", "speed reading" and legalese stuff?

**Comment by Ern-st** [comment]
there is an ical feed on the prosa events page, so maybe we can use https://github.com/icalendar/icalendar to extract the events 😄

**Comment by fALKENdk** [comment]
Prosa's ical feed needs to be updated.
Title is trimmed and description is not provide.

**Comment by fALKENdk** [comment]
Events for fyn: 
https://www.prosa.dk/nc/arrangementer/?tx_news_pi1[overwriteDemand][locations][2]=Fyn
