### ISSUE TITLE
event text gets cropped

### ISSUE THREAD

**Issue by moozer** [fyntech/fyntech#62]
Using the calendar function in thunderbird, I notice that the text associated with an event gets cropped, and it only shows the first part.

![screenshot_2018-12-04_14-57-53](https://user-images.githubusercontent.com/810413/49446708-18be0080-f7d5-11e8-9840-f06d2cdac143.png)

As you may see, the sentence "PROSA UNG inviterer alle PROSA-medlemmer på en hyggelig tur i" stops abruptly and there must be more to it.

**Comment by Ern-st** [comment]
strange that it's stopped working, the problem occurs when we have to split strings longer than 75 octets, when "folding" lines in ICS files you're supposed to insert a new line after the 75th octet then insert a blank space, and then the rest of the line. 

It's been working fine… wondering is the changes to ruby versions that @fALKENdk implemented could have changed something?

The ICS plugins hasen't been touched for a long time https://github.com/fyntech/fyntech/blob/master/_plugins/ics.rb
