### ISSUE TITLE
One event per file

### ISSUE THREAD

**Issue by valberg** [fyntech/fyntech#9]
Instead of having all events in one file we should separate them into their own files.

See https://github.com/moozer/ealtechevents for reference

**Comment by carentsen** [comment]
What do you suggest for sorting them? My suggestion is to have a folder for each event organizer with monthly events, instead of 1event/file

**Comment by moozer** [comment]
I work with collections on ealtechevents. This is not recommended.

I do seperate files for "talks". That is a good idea.

Here I load them and sort them by time
https://github.com/moozer/ealtechevents/blob/gh-pages/_includes/talks_schedule.html

I suggest something similar, but with _data as you do now (*not* collection like I do)

**Comment by fALKENdk** [comment]
#12
